catcollector/urls.py
# catcollector/urls.py

from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')), # Mounts main_app's routes at the root URL
    # direct all web traffic for the root route to the main_app's routes
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views # Import views to connect routes to view functions

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('about/', views.about, name='about'),
    path('cats/', views.cat_index, name='cat-index'),
    path('cats/<int:cat_id>/', views.cat_detail, name='cat-detail'),
    path('cats/create/', views.CatCreate.as_view(), name='cat-create'),
    path('cats/<int:pk>/update/', views.CatUpdate.as_view(), name='cat-update'),
    path('cats/<int:pk>/delete/', views.CatDelete.as_view(), name='cat-delete'),
    path(
        'cats/<int:cat_id>/add-feeding/',
        views.add_feeding,
        name='add-feeding'
    ),
    path('toys/create/', views.ToyCreate.as_view(), name='toy-create'),
    path('toys/<int:pk>/', views.ToyDetail.as_view(), name='toy-detail'),
    path('toys/', views.ToyList.as_view(), name='toy-index'),
    path('toys/<int:pk>/update/', views.ToyUpdate.as_view(), name='toy-update'),
    path('toys/<int:pk>/delete/', views.ToyDelete.as_view(), name='toy-delete'),
    # New URL to associate a toy with a cat
    path('cats/<int:cat_id>/associate-toy/<int:toy_id>/', views.associate_toy, name='associate-toy'),
    path('cats/<int:cat_id>/remove-toy/<int:toy_id>/', views.remove_toy, name='remove-toy'),
    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# A tuple of 2-tuples added above our models
MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner')
)


class Toy(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=20)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('toy-detail', kwargs={'pk': self.id})


class Cat(models.Model):
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField()
    toys = models.ManyToManyField(Toy)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    # Define a method to get the URL for this particular cat instance
    def get_absolute_url(self):
        # Use the 'reverse' function to dynamically find the URL for viewing this cat's details
        return reverse('cat-detail', kwargs={'cat_id': self.id})
    

class Feeding(models.Model):
    date = models.DateField('Feeding Date')
    meal = models.CharField(
        max_length=1,
        # add the 'choices' field option
        choices=MEALS,
        # set the default value for meal to be 'B'
        default=MEALS[0][0]
    )
    cat = models.ForeignKey(Cat, on_delete=models.CASCADE) # delete a cat will delete all its associated feedings

    def __str__(self):
        return f'{self.get_meal_display()} on {self.date}'
        # this will print out breakfast, lunch, dinner
    # Define the default order of feedings
    class Meta:
        ordering = ['-date']  # This line makes the newest feedings appear first

main_app/forms.py
from django import forms
from .models import Feeding

class FeedingForm(forms.ModelForm):
    class Meta:
        model = Feeding
        fields = ['date', 'meal']
        widgets = {
            'date': forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={
                    'placeholder': 'Select a date',
                    'type': 'date'
                }
            ),
        }

main_app/views.py
# main_app/views.py

from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth.views import LoginView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from .models import Cat, Toy
from .forms import FeedingForm
# Import the login_required decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin



# Import HttpResponse to send text-based responses
# from django.http import HttpResponse

class Home(LoginView):
    template_name = 'home.html'

def signup(request):
    error_message = ''
    if request.method == 'POST':
        # This is how to create a 'user' form object
        # that includes the data from the browser
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # This will add the user to the database
            user = form.save()
            # This is how we log a user in
            login(request, user)
            return redirect('cat-index')
        else:
            error_message = 'Invalid sign up - try again'
    # A bad POST or a GET request, so render signup.html with an empty form
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'signup.html', context)
    # Same as: 
    # return render(
    #     request, 
    #     'signup.html',
    #     {'form': form, 'error_message': error_message}
    # )


def about(request):
    contact_details = 'you can reach support at support@catcollector.com'
    return render(request, 'about.html', {
        'contact': contact_details
    })


# Create a simple Cat class and a list of cat instances to simulate a database of cats

# class Cat:
#     def __init__(self, name, breed, description, age):
#         self.name = name
#         self.breed = breed
#         self.description = description
#         self.age = age

# # Create a list of Cat instances
# cats = [
#     Cat('Lolo', 'tabby', 'Kinda rude.', 3),
#     Cat('Sachi', 'tortoiseshell', 'Looks like a turtle.', 0),
#     Cat('Fancy', 'bombay', 'Happy fluff ball.', 4),
#     Cat('Bonk', 'selkirk rex', 'Meows loudly.', 6)
# ]


# Everything in a Python module is automatically exported, 
# thus, the Cat class and the cats list will be accessible in other modules.

@login_required
def cat_index(request):
    cats = Cat.objects.filter(user=request.user)
    # Render the cats/index.html template with the cats data
    return render(request, 'cats/index.html', {'cats': cats})


@login_required
def cat_detail(request, cat_id):
    cat = Cat.objects.get(id=cat_id)
    # Only get the toys the cat does not have
    toys_cat_doesnt_have = Toy.objects.exclude(id__in = cat.toys.all().values_list('id'))
    # instantiate FeedingForm to be rendered in the template
    feeding_form = FeedingForm()
    return render(request, 'cats/detail.html', {
        # include the cat and feeding_form in the context
        'cat': cat, 
        'feeding_form': feeding_form,
        'toys': toys_cat_doesnt_have
    })

@login_required
def add_feeding(request, cat_id):
    # create a ModelForm instance using the data in request.POST
    form = FeedingForm(request.POST)
    # validate the form
    if form.is_valid():
        # don't save the form to the db until it
        # has the cat_id assigned
        new_feeding = form.save(commit=False)
        new_feeding.cat_id = cat_id
        new_feeding.save()
    return redirect('cat-detail', cat_id=cat_id)

@login_required
def associate_toy(request, cat_id, toy_id):
    # Note that you can pass a toy's id instead of the whole object
    Cat.objects.get(id=cat_id).toys.add(toy_id)
    # ^ this finds a particular cat and adds a record to the join
    # table with that cat's id and the id of the toy thus creating the relationship
    return redirect('cat-detail', cat_id=cat_id)

@login_required
def remove_toy(request, cat_id, toy_id):
    # Look up the cat
    # Look up the toy
    # Remove the toy from the cat
    Cat.objects.get(id=cat_id).toys.remove(toy_id)
    return redirect('cat-detail', cat_id=cat_id)


class CatCreate(LoginRequiredMixin,CreateView):
    model = Cat
    fields = ['name', 'breed', 'description', 'age']

    # This inherited method is called when a
    # valid cat form is being submitted
    def form_valid(self, form):
        # Assign the logged in user (self.request.user)
        form.instance.user = self.request.user  # form.instance is the cat
        # Let the CreateView do its job as usual
        return super().form_valid(form)

class CatUpdate(LoginRequiredMixin, UpdateView):
    model = Cat
    fields = ['breed', 'description', 'age']

class CatDelete(LoginRequiredMixin, DeleteView):
    model = Cat
    success_url = '/cats/'

class ToyCreate(LoginRequiredMixin, CreateView):
    model = Toy
    fields = '__all__'

class ToyList(LoginRequiredMixin, ListView):
    model = Toy

class ToyDetail(LoginRequiredMixin, DetailView):
    model = Toy

class ToyUpdate(LoginRequiredMixin, UpdateView):
    model = Toy
    fields = ['name', 'color']

class ToyDelete(LoginRequiredMixin, DeleteView):
    model = Toy
    success_url = '/toys/'

main_app/templates/cats/detail.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href="{% static 'css/cats/cat-detail.css' %}" />
{% endblock %} {% block content %}
<section class="cat-container">
  <div class="cat-img">
    <img src="{% static 'images/sk8r-boi-cat.svg' %}" alt="A skater boy cat" />
  </div>
  <div class="cat-details">
    <h1>{{ cat.name }}</h1>
    {% if cat.age > 0 %}
    <h2>A {{ cat.age }} year old {{ cat.breed }}</h2>
    {% else %}
    <h2>A {{ cat.breed }} kitten.</h2>
    {% endif %}
    <p>{{ cat.description }}</p>

    <div class="cat-actions">
      <a href="{% url 'cat-update' cat.id %}" class="btn warn">Edit</a>
      <a href="{% url 'cat-delete' cat.id %}" class="btn danger">Delete</a>
    </div>
  </div>
</section>

<!-- Existing cat-container above -->
<div class="feedings-toy-container">
  <section class="feedings">
    <div class="subsection-title">
        <h2>Feedings</h2>
        <img src="{% static 'images/cat-cone.svg' %}" alt="An ice cream cone cat" />
        <img src="{% static 'images/cat-onigiri.svg' %}" alt="A cat as onigiri" />
        <img src="{% static 'images/kitty-kabob.svg' %}" alt="A kabob of kittens" />
    </div>
    <h3>Add a Feeding</h3>
    <form
      action="{% url 'add-feeding' cat.id %}"
      method="post"
      class="subsection-content"
      utocomplete="off"
    >
      {% csrf_token %} 
      {{ feeding_form.as_p }}
      <button type="submit" class="btn submit">Add Feeding</button>
    </form>
    <h3>Past Feedings</h3>
    {% if cat.feeding_set.all.count %}
    <table>
      <thead>
        <tr>
          <th>Date</th>
          <th>Meal</th>
        </tr>
      </thead>
      <tbody>
        {% for feeding in cat.feeding_set.all %}
        <tr>
          <td>{{feeding.date}}</td>
          <td>{{feeding.get_meal_display}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <div class="subsection-content">
        <p>⚠️ {{cat.name}} has not been fed!</p>
    {% endif %}
  </section>

  <section class="toys">
    <div class="subsection-title">
      <h2>Toys</h2>
      <img src="{% static 'images/string.svg' %}" alt="A ball of string" />
      <img src="{% static 'images/mouse.svg' %}" alt="A mouse" />
      <img src="{% static 'images/fish.svg' %}" alt="A fishy toy" />
    </div>
        <!-- displaying a cat's toys -->
    <h3>{{ cat.name }}'s Toys</h3>
    <div class="subsection-content">
        {% if cat.toys.count %} 
        {% for toy in cat.toys.all %}
            <div class="toy-container">
            <div class="color-block" style="background-color: {{ toy.color }}"></div>
            <a href="{% url 'toy-detail' toy.id %}">
                <p>A {{ toy.color }} {{ toy.name }}</p>
            </a>
            <form action="{% url 'remove-toy' cat.id toy.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Remove Toy</button>
              </form>              
            </div>
        {% endfor %} 
        {% else %}
        <p class="no-toys">{{cat.name}} doesn't have any toys!</p>
        {% endif %}
    </div>

    <h3>Available Toys</h3>
    <div class="subsection-content">
        {% if toys.count %} 
          {% for toy in toys.all %}
            <div class="toy-container">
              <div class="color-block" style="background-color: {{ toy.color }}"></div>
              <a href="{% url 'toy-detail' toy.id %}">
                <p>A {{ toy.color }} {{ toy.name }}</p>
              </a>
              <form action="{% url 'associate-toy' cat.id toy.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn submit">Give toy</button>
              </form>
            </div>
          {% endfor %} 
        {% else %}
          <p class="all-toys">{{cat.name}} already has all the available toys 🥳</p>
        {% endif %}
      </div>
  </section>
</div>



{% endblock %}

main_app/templates/cats/index.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href="{% static 'css/cats/cat-index.css' %}" />
{% endblock %} {% block content %}

<section class="page-header">
  <h1>Cat List</h1>
  <img src="{% static 'images/cool-cat.svg' %}" alt="A cool cat" />
  <img src="{% static 'images/happy-cat.svg' %}" alt="A happy cat" />
  <img src="{% static 'images/teacup-cat.svg' %}" alt="A cat in a teacup" />
  <img src="{% static 'images/cat-in-box.svg' %}" alt="A cat in a box" />
</section>

<section class="card-container">
  {% for cat in cats %}
  <div class="card">
    <a href="{% url 'cat-detail' cat.id %}">
      <div class="card-content">
        <div class="card-img-container">
          <img
            src="{% static 'images/sk8r-boi-cat.svg' %}"
            alt="A skater boy cat"
          />
        </div>
        <h2 class="card-title">{{ cat.name }}</h2>
        {% if cat.age > 0 %}
        <p>A {{ cat.age }} year old {{ cat.breed }}</p>
        {% else %}
        <p>A {{ cat.breed }} kitten.</p>
        {% endif %}
        <p><small>{{ cat.description }}</small></p>
      </div>
    </a>
  </div>
  {% endfor %}
</section>

{% endblock %}